// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "./Color.bs.js";
import * as Material from "./Material.bs.js";

function dict(key, value) {
  var dict$1 = {};
  dict$1[key] = value;
  return dict$1;
}

function make(color) {
  return Material.make(dict("color", {
                  TAG: "Array",
                  _0: Color.toArray(color)
                }), "#version 300 es\n    uniform mat4 normalMatrix;\n    uniform mat4 projectionMatrix;\n    uniform mat4 modelViewMatrix;\n    in vec3 position;\n    in vec3 normal;\n    out vec3 vNormal;\n\n    void main() {\n      vNormal = (normalMatrix * vec4(normal, 0)).xyz;\n      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);\n    }\n  ", "#version 300 es\n    precision lowp float;\n\n    uniform vec3 color;\n    in vec3 vNormal;\n    out vec4 pc_fragColor;\n\n    void main() {\n      float lighting = dot(vNormal, normalize(vec3(10)));\n      pc_fragColor = vec4(color + lighting * 0.1, 1.0);\n    }\n  ", undefined, undefined, undefined, undefined, undefined);
}

export {
  dict ,
  make ,
}
/* No side effect */
