// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Frustum from "./Frustum.bs.js";
import * as Matrix4 from "./Matrix4.bs.js";

function make() {
  return {
          projectionMatrix: Matrix4.make(),
          viewMatrix: Matrix4.make(),
          projectionViewMatrix: Matrix4.make(),
          frustum: Frustum.make(),
          fov: 90.0,
          aspect: 1.0,
          near: 0.1,
          far: 1000.0
        };
}

function updateMatrix($$this, objectMatrix) {
  Matrix4.invert(Matrix4.copy($$this.viewMatrix, objectMatrix));
  Matrix4.perspective($$this.projectionMatrix, $$this.fov, $$this.aspect, $$this.near, $$this.far);
}

export {
  make ,
  updateMatrix ,
}
/* Matrix4 Not a pure module */
