// Generated by ReScript, PLEASE EDIT WITH CARE


function toArray(t) {
  var tmp;
  tmp = typeof t !== "object" ? (
      t === "Red" ? [
          255,
          0,
          0
        ] : [
          255,
          255,
          255
        ]
    ) : [
      t._0,
      t._1,
      t._2
    ];
  return tmp.map(function (prim) {
              return prim;
            });
}

export {
  toArray ,
}
/* No side effect */
