// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return new WeakMap();
}

function get(t, a) {
  return t.get(a);
}

function set(t, a, v) {
  t.set(a, v);
}

export {
  make ,
  get ,
  set ,
}
/* No side effect */
