// Generated by ReScript, PLEASE EDIT WITH CARE


function make(size, data) {
  return {
          data: data,
          size: size,
          needsUpdate: false
        };
}

var Attribute = {
  make: make
};

function make$1(a) {
  var attributes = {};
  a.forEach(function (param) {
        var name = param[0];
        attributes[name] = param[1];
        attributes[name].needsUpdate = true;
      });
  return {
          drawRange: {
            start: 0,
            count: 9999999
          },
          attributes: attributes
        };
}

export {
  Attribute ,
  make$1 as make,
}
/* No side effect */
