// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make(uniformsOpt, vertex, fragment, sideOpt, transparentOpt, depthTestOpt, depthWriteOpt, blendingOpt) {
  var uniforms = uniformsOpt !== undefined ? uniformsOpt : ({});
  var side = sideOpt !== undefined ? sideOpt : "Front";
  var transparent = transparentOpt !== undefined ? transparentOpt : false;
  var depthTest = depthTestOpt !== undefined ? depthTestOpt : true;
  var depthWrite = depthWriteOpt !== undefined ? depthWriteOpt : true;
  var blending = blendingOpt !== undefined ? Caml_option.valFromOption(blendingOpt) : undefined;
  return {
          uniforms: uniforms,
          vertex: vertex,
          fragment: fragment,
          side: side,
          transparent: transparent,
          depthTest: depthTest,
          depthWrite: depthWrite,
          blending: blending
        };
}

export {
  make ,
}
/* No side effect */
