// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Matrix4 from "./Matrix4.bs.js";

function make(geometry, material) {
  return {
          modelViewMatrix: Matrix4.make(),
          normalMatrix: Matrix4.make(),
          mode: "Triangles",
          instances: 1,
          geometry: geometry,
          material: material
        };
}

export {
  make ,
}
/* Matrix4 Not a pure module */
