// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Matrix4 from "./Matrix4.bs.js";

function compose($$this, position, quaternion, scale) {
  var xx = 2.0 * quaternion.x * quaternion.x;
  var xy = 2.0 * quaternion.y * quaternion.x;
  var xz = 2.0 * quaternion.z * quaternion.x;
  var yy = 2.0 * quaternion.y * quaternion.y;
  var yz = 2.0 * quaternion.z * quaternion.y;
  var zz = 2.0 * quaternion.z * quaternion.z;
  var wx = 2.0 * quaternion.x * quaternion.w;
  var wy = 2.0 * quaternion.y * quaternion.w;
  var wz = 2.0 * quaternion.z * quaternion.w;
  return Matrix4.set($$this, [
              (1.0 - (yy + zz)) * scale.x,
              (xy + wz) * scale.x,
              (xz - wy) * scale.x,
              0.0,
              (xy - wz) * scale.y,
              (1.0 - (xx + zz)) * scale.y,
              (yz + wx) * scale.y,
              0.0,
              (xz + wy) * scale.z,
              (yz - wx) * scale.z,
              (1.0 - (xx + yy)) * scale.z,
              0.0,
              position.x,
              position.y,
              position.z,
              1.0
            ]);
}

export {
  compose ,
}
/* Matrix4 Not a pure module */
