// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Node from "./Node.bs.js";
import * as Vector3 from "./Vector3.bs.js";

function make(camera) {
  var center = Vector3.make(0.0, 0.0, 0.0);
  return $$Node.lookAt(camera, center);
}

export {
  make ,
}
/* Node Not a pure module */
