// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Texture from "./Texture.bs.js";

function make(width, height, countOpt) {
  var count = countOpt !== undefined ? countOpt : 1;
  return {
          textures: [Texture.make(undefined, undefined, undefined, undefined, undefined, undefined)],
          needsUpdate: true,
          width: width,
          height: height,
          count: count
        };
}

export {
  make ,
}
/* No side effect */
