// Generated by ReScript, PLEASE EDIT WITH CARE


function jsx(a, b) {
  return a(b);
}

function jsxs(a, b) {
  return a(b);
}

function array(a) {
  return a;
}

export {
  jsx ,
  jsxs ,
  array ,
}
/* No side effect */
