// Generated by ReScript, PLEASE EDIT WITH CARE


function make(magFilterOpt, minFilterOpt, wrapSOpt, wrapTOpt, anisotropyOpt, needsUpdateOpt, param) {
  var magFilter = magFilterOpt !== undefined ? magFilterOpt : "Nearest";
  var minFilter = minFilterOpt !== undefined ? minFilterOpt : "Nearest";
  var wrapS = wrapSOpt !== undefined ? wrapSOpt : "Clamp";
  var wrapT = wrapTOpt !== undefined ? wrapTOpt : "Clamp";
  var anisotropy = anisotropyOpt !== undefined ? anisotropyOpt : 1.0;
  var needsUpdate = needsUpdateOpt !== undefined ? needsUpdateOpt : true;
  return {
          magFilter: magFilter,
          minFilter: minFilter,
          wrapS: wrapS,
          wrapT: wrapT,
          anisotropy: anisotropy,
          needsUpdate: needsUpdate
        };
}

export {
  make ,
}
/* No side effect */
