// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sampler from "./Sampler.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make(imageOpt, samplerOpt, formatOpt, textureTypeOpt, needsUpdateOpt, param) {
  var image = imageOpt !== undefined ? Caml_option.valFromOption(imageOpt) : undefined;
  var sampler = samplerOpt !== undefined ? samplerOpt : Sampler.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var format = formatOpt !== undefined ? Caml_option.valFromOption(formatOpt) : undefined;
  var textureType = textureTypeOpt !== undefined ? Caml_option.valFromOption(textureTypeOpt) : undefined;
  var needsUpdate = needsUpdateOpt !== undefined ? needsUpdateOpt : true;
  return {
          sampler: sampler,
          image: image,
          format: format,
          textureType: textureType,
          needsUpdate: needsUpdate
        };
}

export {
  make ,
}
/* No side effect */
