// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function float32Array(arr) {
  return {
          TAG: "Float32Array",
          _0: Float32Array.from(arr)
        };
}

function uint16Array(arr) {
  return {
          TAG: "Uint16Array",
          _0: Uint16Array.from(arr)
        };
}

function length(t) {
  return t._0.length;
}

function $$float(t) {
  if (t.TAG === "Float32Array") {
    return t._0;
  } else {
    return PervasivesU.failwith("meh this is int");
  }
}

function $$int(t) {
  if (t.TAG === "Float32Array") {
    return PervasivesU.failwith("meh this is float");
  } else {
    return t._0;
  }
}

function bytesPerElement(t) {
  return t._0.BYTES_PER_ELEMENT;
}

export {
  float32Array ,
  uint16Array ,
  length ,
  $$float ,
  $$int ,
  bytesPerElement ,
}
/* No side effect */
