// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function hypot(prim) {
  return Caml_splice_call.spliceApply(Math.hypot, [prim]);
}

var pi = Math.PI;

var epsilon = 0.000001;

export {
  hypot ,
  pi ,
  epsilon ,
}
/* pi Not a pure module */
