// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Global from "./Global.bs.js";
import * as Quaternion from "./Quaternion.bs.js";
import * as WebGLRenderer from "./WebGLRenderer.bs.js";

var renderer = WebGLRenderer.make();

WebGLRenderer.setSize(renderer, 1000, 1000);

var camera = Global.camera();

camera.position.z = 5.0;

function makeRotation(thing) {
  var angle = {
    contents: 0.0
  };
  return {
          update: (function () {
              var a = angle.contents;
              Quaternion.fromEuler(thing.quaternion, a, a, a);
              angle.contents = angle.contents + 0.01;
            })
        };
}

var cube = Global.mesh(Global.cubeGeometry(), Global.basicMaterial("Red"));

var scene = Global.group([cube]);

var rotator = makeRotation(cube);

function animate() {
  WebGLRenderer.render(renderer, scene, camera);
  rotator.update();
  cube.quaternion.x = cube.quaternion.x + 0.1;
  cube.quaternion.y = cube.quaternion.y + 0.1;
}

animate();

export {
  renderer ,
  camera ,
  makeRotation ,
  cube ,
  scene ,
  rotator ,
  animate ,
}
/* renderer Not a pure module */
