// Generated by ReScript, PLEASE EDIT WITH CARE


function gl_filters(filter) {
  if (filter === "Nearest") {
    return 9728;
  } else {
    return 9729;
  }
}

function gl_wrappings(wrapping) {
  switch (wrapping) {
    case "Clamp" :
        return 33071;
    case "Repeat" :
        return 10497;
    case "Mirror" :
        return 33648;
    
  }
}

function gl_blend_factors(blendFactor) {
  if (blendFactor === "Zero") {
    return 0;
  } else {
    return 1;
  }
}

function gl_blend_operations(op) {
  switch (op) {
    case "Add" :
        return 32774;
    case "Subtract" :
        return 32778;
    case "ReverseSubtract" :
        return 32779;
    case "Min" :
        return 32775;
    case "Max" :
        return 32776;
    
  }
}

var gl_FRAMEBUFFER = 36160;

var gl_COLOR_ATTACHMENT0 = 36064;

var gl_TEXTURE_2D = 3553;

var gl_TEXTURE_MAG_FILTER = 10240;

var gl_TEXTURE_MIN_FILTER = 10241;

var gl_TEXTURE_WRAP_S = 10242;

var gl_TEXTURE_WRAP_T = 10243;

var gl_RGBA = 6408;

var gl_DEPTH_TEST = 2929;

var gl_CULL_FACE = 2884;

var gl_BLEND = 3042;

var gl_UNPACK_ALIGNMENT = 3317;

var gl_VERTEX_SHADER = 35633;

var gl_FRAGMENT_SHADER = 35632;

var gl_ELEMENT_ARRAY_BUFFER = 34963;

var gl_ARRAY_BUFFER = 34962;

var gl_STATIC_DRAW = 35044;

var gl_DYNAMIC_DRAW = 35048;

var gl_COLOR_BUFFER_BIT = 16384;

var gl_DEPTH_BUFFER_BIT = 256;

var gl_STENCIL_BUFFER_BIT = 1024;

var gl_LESS = 513;

var gl_FRONT = 1028;

var gl_BACK = 1029;

var gl_TEXTURE0 = 33984;

var gl_POINTS = 0;

var gl_TRANSFORM_FEEDBACK = 36386;

var gl_TRANSFORM_FEEDBACK_BUFFER = 35982;

var gl_SEPARATE_ATTRIBS = 35981;

var gl_RASTERIZER_DISCARD = 35977;

var gl_NEAREST = 9728;

var gl_LINEAR = 9729;

var gl_REPEAT = 10497;

var gl_CLAMP_TO_EDGE = 33071;

var gl_MIRRORED_REPEAT = 33648;

var gl_ZERO = 0;

var gl_ONE = 1;

var gl_SRC_COLOR = 768;

var gl_ONE_MINUS_SRC_COLOR = 769;

var gl_SRC_ALPHA = 770;

var gl_ONE_MINUS_SRC_ALPHA = 771;

var gl_DST_COLOR = 774;

var gl_DST_ALPHA = 772;

var gl_ONE_MINUS_DST_ALPHA = 773;

var gl_ONE_MINUS_DST_COLOR = 775;

var gl_SRC_ALPHA_SATURATE = 776;

var gl_letANT_COLOR = 32769;

var gl_ONE_MINUS_letANT_COLOR = 32770;

var gl_FUNC_ADD = 32774;

var gl_FUNC_SUBSTRACT = 32778;

var gl_FUNC_REVERSE_SUBTRACT = 32779;

var gl_MIN = 32775;

var gl_MAX = 32776;

var gl_FLOAT = 5126;

var gl_BYTE = 5120;

var gl_SHORT = 5122;

var gl_INT = 5124;

var gl_UNSIGNED_BYTE = 5121;

var gl_UNSIGNED_SHORT = 5123;

var gl_UNSIGNED_INT = 5125;

export {
  gl_FRAMEBUFFER ,
  gl_COLOR_ATTACHMENT0 ,
  gl_TEXTURE_2D ,
  gl_TEXTURE_MAG_FILTER ,
  gl_TEXTURE_MIN_FILTER ,
  gl_TEXTURE_WRAP_S ,
  gl_TEXTURE_WRAP_T ,
  gl_RGBA ,
  gl_DEPTH_TEST ,
  gl_CULL_FACE ,
  gl_BLEND ,
  gl_UNPACK_ALIGNMENT ,
  gl_VERTEX_SHADER ,
  gl_FRAGMENT_SHADER ,
  gl_ELEMENT_ARRAY_BUFFER ,
  gl_ARRAY_BUFFER ,
  gl_STATIC_DRAW ,
  gl_DYNAMIC_DRAW ,
  gl_COLOR_BUFFER_BIT ,
  gl_DEPTH_BUFFER_BIT ,
  gl_STENCIL_BUFFER_BIT ,
  gl_LESS ,
  gl_FRONT ,
  gl_BACK ,
  gl_TEXTURE0 ,
  gl_POINTS ,
  gl_TRANSFORM_FEEDBACK ,
  gl_TRANSFORM_FEEDBACK_BUFFER ,
  gl_SEPARATE_ATTRIBS ,
  gl_RASTERIZER_DISCARD ,
  gl_NEAREST ,
  gl_LINEAR ,
  gl_filters ,
  gl_REPEAT ,
  gl_CLAMP_TO_EDGE ,
  gl_MIRRORED_REPEAT ,
  gl_wrappings ,
  gl_ZERO ,
  gl_ONE ,
  gl_SRC_COLOR ,
  gl_ONE_MINUS_SRC_COLOR ,
  gl_SRC_ALPHA ,
  gl_ONE_MINUS_SRC_ALPHA ,
  gl_DST_COLOR ,
  gl_DST_ALPHA ,
  gl_ONE_MINUS_DST_ALPHA ,
  gl_ONE_MINUS_DST_COLOR ,
  gl_SRC_ALPHA_SATURATE ,
  gl_letANT_COLOR ,
  gl_ONE_MINUS_letANT_COLOR ,
  gl_blend_factors ,
  gl_FUNC_ADD ,
  gl_FUNC_SUBSTRACT ,
  gl_FUNC_REVERSE_SUBTRACT ,
  gl_MIN ,
  gl_MAX ,
  gl_blend_operations ,
  gl_FLOAT ,
  gl_BYTE ,
  gl_SHORT ,
  gl_INT ,
  gl_UNSIGNED_BYTE ,
  gl_UNSIGNED_SHORT ,
  gl_UNSIGNED_INT ,
}
/* No side effect */
